name: Python Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright allure-pytest

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Run Playwright tests with Allure
        run: |
          pytest --browser chromium --alluredir=allure-results

      - name: Download Allure
        run: |
          Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip" -OutFile "allure.zip"
          Expand-Archive -Path "allure.zip" -DestinationPath "C:\allure"
          $env:Path += ";C:\allure\allure-2.21.0\bin"

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report